### ISSUE TITLE
Consistent warnings for get_user

### ISSUE THREAD

**Issue by christopher-dG** [khazhyk/osuapi#15]
Haven't looked into this much but here's the output:

```
>>> api.get_user("peppy")
/home/degraafc/.virtualenvs/osubot/lib/python3.6/site-packages/osuapi/dictmodel.py:49: Warning: Unknown attribute count_rank_ssh in API response for type <class 'osuapi.model.User'>
  warnings.warn("Unknown attribute {} in API response for type {}".format(k, type(self)), Warning)
/home/degraafc/.virtualenvs/osubot/lib/python3.6/site-packages/osuapi/dictmodel.py:49: Warning: Unknown attribute count_rank_sh in API response for type <class 'osuapi.model.User'>
  warnings.warn("Unknown attribute {} in API response for type {}".format(k, type(self)), Warning)
[<osuapi.model.User username=peppy user_id=2>]

```

**Comment by khazhyk** [comment]
nice, these warnings actually work as intended :) Looks like the API now exposes the S/SS hidden ranks separately from S/SS. Thanks for reporting.

Looks like https://github.com/ppy/osu-api/wiki hasn't been updated yet for what these values mean...

It looks like SSH and SS are exclusive (so SSH + SS = total number of SS you have, where SSH are the silver SS. S/SH looks broken, both of them return the same number for all users (it looks like their normal S count).

Adding support in 0.0.27

**Comment by christopher-dG** [comment]
Relevant issue: https://github.com/ppy/osu-api/issues/204

**Comment by khazhyk** [comment]
0.0.27 pushed to pypi
