### ISSUE TITLE
Unhandled connection closed

### ISSUE THREAD

**Issue by ren-** [khazhyk/osuapi#23]
https://github.com/khazhyk/osuapi/blob/19cb80aad8035e103eb402127fef15c1f8d0a2c1/osuapi/connectors.py#L47-L62

I believe your logic was that 
` raise HTTPError(resp.status, resp.reason, 
                 (yield from resp.text())) ` 

Would return existing response text even if the response object is closed.

However, this is not the case with the empty body:

https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L913-L922

Forcing a read on a closed object.

`elif resp.status == 504 and retries:` the loop wouldn't run if the retries variable was negative or 0, so this is unnecessary.

**Comment by khazhyk** [comment]
I'm not sure what you mean by "case with the empty body"

```py
import aiohttp, asyncio
loop = asyncio.get_event_loop
a = loop.run_until_complete

s = aiohttp.ClientSession(loop=loop)
res = a(s.head("https://google.com))
res.close()
res._body
a(res.text()) ''
res._body  # b''
a(res.text()) ''
```

**Comment by khazhyk** [comment]
Should be fixed
