### ISSUE TITLE
hash and eq for SoloScore based on score_id?

### ISSUE THREAD

**Issue by YaLTeR** [khazhyk/osuapi#29]
I needed to store scores in a set, so I added this to `SoloScore`:
```python
    def __hash__(self):
        return hash(self.score_id)

    def __eq__(self, other):
        return self.score_id == other.score_id
```
which works as it should for my purposes. Would a PR with that be fine, or is this too specific to my use-case?

**Comment by khazhyk** [comment]
seems fine

**Comment by khazhyk** [comment]
66b83cc785bb1c550b93d8556ceb0e2e7f068f5a
