### ISSUE TITLE
Functions not returning all attributes

### ISSUE THREAD

**Issue by iceCuube** [khazhyk/osuapi#37]
get_user_best seems to only return user_id, beatmap_id and date. accessing other attributes such as PP only returns with attribute error, not found

similar to this is get_beatmaps only returning title, creator and id

**Comment by khazhyk** [comment]
Can you give an example that doesn't work?

**Comment by iceCuube** [comment]
nvm i fixed it and i dont know how i did it or how to reproduce it

sorry for wasting your time
