### ISSUE TITLE
Circular import !

### ISSUE THREAD

**Issue by Renondedju** [khazhyk/osuapi#8]
I simply can't import ReqConnector due to a circular import ...

Traceback (most recent call last):
  File "UsoDiscord.py", line 21, in <module>
    from osuapi import OsuMode, BeatmapStatus, OsuApi, ReqConnector
ImportError: cannot import name 'ReqConnector'

(It was working fine on an old machine)

**Comment by khazhyk** [comment]
Cannot reproduce.

What version are you on? You may be out of date.

```
>>> from osuapi import OsuMode, BeatmapStatus, OsuApi, ReqConnector
>>> 
```

**Comment by Renondedju** [comment]
python 3.5.3
I'm using  ARMBIAN 5.31 stable Debian GNU/Linux 8 (jessie) 4.11.6-sunxi on a cubieboard 3 (cubietruck)
And i dowloaded like 4 hours ago your library

**Comment by khazhyk** [comment]
What version of the library are you using?

**Comment by khazhyk** [comment]
Oh, caveat: in order to be able to import ReqConnector, you must have 'requests' installed. This perhaps isn't as clear as it should be.

**Comment by Renondedju** [comment]
oh thats maybe why, can you tell me how to install requests ?

**Comment by Renondedju** [comment]
And the version of the library is the last one

**Comment by khazhyk** [comment]
The same as installing osuapi - `pip install requests`

**Comment by Renondedju** [comment]
This is working now fine ! Thanks !
